apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: simple-webapp
  template:
    metadata:
      labels:
        name: simple-webapp
    spec:
      containers:
      - image: kodekloud/simple-webapp:red
        name: simple-webapp
        ports:
        - containerPort: 8080
          protocol: TCP